name: 运行 生成m3u

on:
  schedule:
    # 每天北京时间中午 12:00 自动运行一次 (UTC 04:00)
    - cron: '30 4 * * *'
  workflow_dispatch: # 允许在 GitHub 页面手动点击运行

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: 1. 检出当前代码库
        uses: actions/checkout@v4

      - name: 2. Python 环境准备
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. 安装依赖
        run: pip install requests urllib3

      - name: 4. 执行扫描脚本
        run: python -u py/convert.py

      - name: 5. 自动提交并推送扫描结果到当前仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .
          
          if git diff --staged --quiet; then
            echo "✨ 扫描完成，结果无变动，跳过推送。"
          else
            git commit -m "自动更新 C段扫描存活结果及独立hotels文件: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
